### ISSUE TITLE
Thought about states not in the US?

### ISSUE THREAD

**Issue by judgej** [adrianmejias/laravel-states#3]
Other countries around the world have states, or the equivalent of states. It would be great IMO to be able to support those too, especially as this package is named so generically (i.e. not "US States").

Just adding a country code column to the model and loading it with "US" for the current seed data would be a fantastic start.

**Comment by scottconnerly** [comment]
Has Github implemented that +1 feature yet? I don't think so. So... +1. International regions would be super handy.

**Comment by adrianmejias** [comment]
Yeah, I thought about that but was already down the rabbit hole for naming. I'm not sure if names get released in packages but I'll stick with 'laravel-states' until then.

I've added a 'country_code' in develop and will be testing this. I should have something ready in a few. Thanks guys!
